local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("Doors Morph", "GrapeTheme")
 
local Tab1 = Window:NewTab("Morph")
local Tab1Section = Tab1:NewSection("Morph")
local Tab1Section = Tab1:NewSection("More Coming Soon!")
 
Tab1Section:NewButton("Dread", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12448942503")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("A278", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449125066")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("A-120", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12448839736")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("A-60", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12448751167")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("A-25", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12448803816")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Ambush", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449031047")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Rush", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449041111")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Trollface", "...", function()
    local Ambush = game:GetObjects("rbxassetid://11541624412")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Depth", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449166761")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Silence", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449182945")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("Greed", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449205488")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)

Tab1Section:NewButton("LSPLASH", "...", function()
    local Ambush = game:GetObjects("rbxassetid://12449228760")[1] for i,v in pairs(game.Workspace:GetChildren()) do if v.Name == "Ambush" then v:Destroy() end end for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do if v:IsA("MeshPart") then v.Transparency = 1 end if v:IsA("Part") then v.Transparency = 1 end if v:IsA("Accessory") then v:Destroy() end game.Players.LocalPlayer.Character.Head.face.Transparency = 1 end Ambush.Parent = game.Workspace Ambush.Torso.Anchored = true game:GetService("RunService").RenderStepped:Connect(function() Ambush:PivotTo(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 1, 0)) game.Workspace.CurrentCamera.CFrame = (game.Players.LocalPlayer.Character.Head.CFrame * CFrame.Angles(math.rad(-30),0,0)) * CFrame.new(0,0.5,10) game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 20 end) -- -- -- -- -- -- -- ---- -- ------ ---- ---- ---
end)
